modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="simpledeserteagle"
version="1.7.0"
displayName="SimpleDesertEagle"
credits="Programmer:LZY_Pinero Texture:Ankonzy"
displayURL="https://github.com/GaylordFockerCN/SimpleDesertEagle"
authors="LZY_Pinero"
description="阿巴阿巴阿巴懒得再写了看github吧"

[[dependencies.simpledeserteagle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.simpledeserteagle]]
    modId="geckolib"
    mandatory=false
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"

